# Analysis options for Flutter project
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
    - "**/l10n/**"

linter:
  rules:
    # Error rules
    avoid_slow_async_io: true
    cancel_subscriptions: true
    literal_only_boolean_expressions: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    
    # Style rules
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    avoid_classes_with_only_static_members: true
    avoid_function_literals_in_foreach_calls: true
    avoid_positional_boolean_parameters: true
    avoid_private_typedef_functions: true
    avoid_returning_null_for_void: true
    avoid_unused_constructor_parameters: true
    cascade_invocations: true
    directives_ordering: true
    file_names: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    sort_child_properties_last: true
    sort_constructors_first: true
    unawaited_futures: true
    use_key_in_widget_constructors: true
